language: scala

scala:
   - 2.12.2

services:
  - docker

script:
  - sbt compile
  - sbt clean coverage test coverageReport && sbt coverageAggregate

# see also https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

after_success:
  - sbt coveralls
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"